<?php

return array(
    'type'=>array(
        'title'=>'开启同步登录：',
        'type'=>'checkbox',
        'options'=>array(
            'Qq'=>'Qq',
            'Sina'=>'Sina',
		    'Tencent'=>'腾讯微博',
			'Renren'=>'人人网',
			'Douban'=>'豆瓣',
			'Github'=>'Github',
			'Google'=>'google',
			'Msn'=>'msn',
			'Diandian'=>'点点',
			'Taobao'=>'淘宝网',
			'Baidu'=>'百度',
			'Kaixin'=>'开心网',
			 'T163'=>'网易微博',
		    'X360'=>'360',
			'Sohu'=>'搜狐微博'
        )
    ),
    'meta'=>array(//配置在表单中的键名 ,这个会是config[title]
        'title'=>'接口验证代码：',//表单的文字
        'type'=>'textarea',         //表单的类型：text、textarea、checkbox、radio、select等
        'value'=>'1',             //表单的默认值
        'tip'=>'需要在Meta标签中写入验证信息时，拷贝代码到这里。'
    ),

'group'=>array(
		'title'=>'登录插件配置:',
		'type'=>'group',
		'options'=>array(
			'Qq'=>array(
				'title'=>'QQ',
				'options'=>array(
					'QqKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'QqSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'Tencent'=>array(
				'title'=>'腾讯微博',
				'options'=>array(
					'TencentKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'TencentSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'Sina'=>array(
				'title'=>'新浪微博',
				'options'=>array(
					'SinaKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'SinaSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'T163'=>array(
				'title'=>'网易微博',
				'options'=>array(
					'T163KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'T163Secret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'Renren'=>array(
				'title'=>'人人网',
				'options'=>array(
					'RenrenKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'RenrenSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'X360'=>array(
				'title'=>'360',
				'options'=>array(
					'X360KEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'X360Secret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'Douban'=>array(
				'title'=>'豆瓣',
				'options'=>array(
					'DoubanKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'DoubanSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'Github'=>array(
				'title'=>'Github',
				'options'=>array(
					'GithubKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'GithubSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'Google'=>array(
				'title'=>'Google',
				'options'=>array(
					'GoogleKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'GoogleSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),		
				'Msn'=>array(
				'title'=>'Msn',
				'options'=>array(
					'MsnKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'MsnSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),	
				'Diandian'=>array(
				'title'=>'点点',
				'options'=>array(
					'DiandianKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'DiandianSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),	
				'Taobao'=>array(
				'title'=>'淘宝网',
				'options'=>array(
					'TaobaoKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'TaobaoSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),	
				'Baidu'=>array(
				'title'=>'百度',
				'options'=>array(
					'BaiduKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'BaiduSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),	
				'Kaixin'=>array(
				'title'=>'开心网',
				'options'=>array(
					'KaixinKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'KaixinSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),
				'Sohu'=>array(
				'title'=>'搜狐微博',
				'options'=>array(
					'SohuKEY'=>array(
						'title'=>'APP_KEY:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
					'SohuSecret'=>array(
						'title'=>'APP_SECRET:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>''
					),
				)
			),						

	)),
		
);
